print("=====================================================================")
nama = input("masukan nama lengkap  : ")
nim = input("masukan nim anda      : ")
jurusan = input("jurusan               : ")
alamat = input("alamat                : ")
print("=====================================================================")
print("Hasil cetak data diatas adalah   : ")
print("Nama anda adalah     : ", nama, ", Nim anda adalah      : ", nim)
print("jurusan anda adalah  : ", jurusan, ", Alamat anda adalah      : ", alamat)
print("=====================================================================")