print(                          "*********TOKO MAINAN ANAK*********"              )
print(                          "=================================="              )
nama = input("Masukan Nama Pembeli   : ")
kode = input("Masukan Kode Mainan    : ")
harga = int(input("Masukan harga     : "))  
beli = int(input("Masukan Jumlah beli : "))
print("====================================")
print("Nama pembeli : ",nama)
print("Kode Mainan  : ",kode)
print("Harga        : ",harga)
print("Jumlh Beli   : ",beli)
jumlah = harga * beli
print("Total        : ",jumlah)